import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#00513f",
        "surface": "#12122A",
        "primary-container": "#fc536d",
        "on-secondary-container": "#005441",
        "surface-container": "#1e1e2c",
        "on-background": "#e3e0f4",
        "error": "#ffb4ab",
        "surface-container-highest": "#343342",
        "surface-container-high": "#292937",
        "on-primary-fixed-variant": "#91002b",
        "surface-container-low": "#1a1a28",
        "primary-fixed": "#ffdadb",
        "inverse-on-surface": "#2f2f3d",
        "background": "#12121f",
        "inverse-primary": "#b71d3f",
        "tertiary": "#67dc9f",
        "on-tertiary-container": "#00311c",
        "on-secondary-fixed": "#002118",
        "secondary": "#41eec2",
        "on-tertiary-fixed": "#002111",
        "on-primary-container": "#5b0017",
        "tertiary-fixed-dim": "#67dc9f",
        "primary-fixed-dim": "#ffb2b7",
        "secondary-container": "#00d1a7",
        "dot-grid": "#2A2A4A",
        "outline-variant": "#5a4042",
        "error-container": "#93000a",
        "text-secondary": "#8888AA",
        "surface-dim": "#12121f",
        "surface-elevated": "#1A1A3E",
        "outline": "#a9898a",
        "secondary-fixed-dim": "#28dfb5",
        "on-primary-fixed": "#40000e",
        "on-error-container": "#ffdad6",
        "border-subtle": "#2A2A4A",
        "text-primary": "#F0F0FF",
        "on-tertiary-fixed-variant": "#005232",
        "surface-bright": "#383847",
        "on-surface": "#e3e0f4",
        "tertiary-fixed": "#84f9ba",
        "on-error": "#690005",
        "on-surface-variant": "#e2bebf",
        "on-tertiary": "#003921",
        "primary": "#ffb2b7",
        "inverse-surface": "#e3e0f4",
        "tertiary-container": "#25a46d",
        "on-primary": "#67001c",
        "surface-tint": "#ffb2b7",
        "surface-container-lowest": "#0d0d1a",
        "on-secondary": "#00382b",
        "surface-variant": "#343342",
        "secondary-fixed": "#55fcd0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "120px",
        "grid-unit": "8px",
        "gutter": "24px",
        "dot-spacing": "32px",
        "max-width": "1280px",
        "navbar-height": "72px",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
        "code-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "max-width": "1280px",
      },
      backgroundImage: {
        "dot-grid": "radial-gradient(#2A2A4A 1px, transparent 1px)",
      },
      backgroundSize: {
        "dot-grid": "32px 32px",
      },
    },
  },
  plugins: [],
};

export default config;
